//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineAntibes.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CineAntibes.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string MenuTitle {
            get {
                return ResourceManager.GetString("MenuTitle", resourceCulture);
            }
        }
        
        public static string ScheduleTitle {
            get {
                return ResourceManager.GetString("ScheduleTitle", resourceCulture);
            }
        }
        
        public static string WhatsOnTitle {
            get {
                return ResourceManager.GetString("WhatsOnTitle", resourceCulture);
            }
        }
        
        public static string ComingSoonTitle {
            get {
                return ResourceManager.GetString("ComingSoonTitle", resourceCulture);
            }
        }
        
        public static string WithinAnHourTitle {
            get {
                return ResourceManager.GetString("WithinAnHourTitle", resourceCulture);
            }
        }
        
        public static string ReservationTitle {
            get {
                return ResourceManager.GetString("ReservationTitle", resourceCulture);
            }
        }
        
        public static string MovieBy {
            get {
                return ResourceManager.GetString("MovieBy", resourceCulture);
            }
        }
        
        public static string MovieRating {
            get {
                return ResourceManager.GetString("MovieRating", resourceCulture);
            }
        }
        
        public static string MovieNextSession {
            get {
                return ResourceManager.GetString("MovieNextSession", resourceCulture);
            }
        }
        
        public static string NoNextSession {
            get {
                return ResourceManager.GetString("NoNextSession", resourceCulture);
            }
        }
        
        public static string MovieReleaseDate {
            get {
                return ResourceManager.GetString("MovieReleaseDate", resourceCulture);
            }
        }
        
        public static string MovieBookButton {
            get {
                return ResourceManager.GetString("MovieBookButton", resourceCulture);
            }
        }
        
        public static string VFSessionsSection {
            get {
                return ResourceManager.GetString("VFSessionsSection", resourceCulture);
            }
        }
        
        public static string VOSessionsSection {
            get {
                return ResourceManager.GetString("VOSessionsSection", resourceCulture);
            }
        }
        
        public static string MovieDirectoreAndStars {
            get {
                return ResourceManager.GetString("MovieDirectoreAndStars", resourceCulture);
            }
        }
        
        public static string MovieSynopsis {
            get {
                return ResourceManager.GetString("MovieSynopsis", resourceCulture);
            }
        }
        
        public static string MoviePhotos {
            get {
                return ResourceManager.GetString("MoviePhotos", resourceCulture);
            }
        }
        
        public static string MovieRealizedBy {
            get {
                return ResourceManager.GetString("MovieRealizedBy", resourceCulture);
            }
        }
        
        public static string MovieWith {
            get {
                return ResourceManager.GetString("MovieWith", resourceCulture);
            }
        }
        
        public static string SessionDateFormat {
            get {
                return ResourceManager.GetString("SessionDateFormat", resourceCulture);
            }
        }
        
        public static string ReleaseDateFormat {
            get {
                return ResourceManager.GetString("ReleaseDateFormat", resourceCulture);
            }
        }
        
        public static string HourDateFormat {
            get {
                return ResourceManager.GetString("HourDateFormat", resourceCulture);
            }
        }
        
        public static string LoadingMessage {
            get {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }
    }
}
